// <auto-generated />
namespace EF5.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class iNITIAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iNITIAL));
        
        string IMigrationMetadata.Id
        {
            get { return "201301070911212_iNITIAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
